Repository asdvsvs/my-paldo-trip, pull requests merged in 2024-02, with the labels that each got.

#146 여행정보 서비스 테스트코드
  src/test/java/com/b6/mypaldotrip/domain/trip/TripTest.java
  src/test/java/com/b6/mypaldotrip/domain/trip/service/TripServiceTest.java
Labels: test

#143 Course Controller Test
  src/main/java/com/b6/mypaldotrip/domain/comment/controller/dto/request/CommentSaveReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/CourseController.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/request/CourseSaveReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/request/CourseSearchReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/request/CourseUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/service/CourseService.java
  src/test/java/com/b6/mypaldotrip/domain/course/BaseCourseTest.java
  src/test/java/com/b6/mypaldotrip/domain/course/CourseTest.java
  src/test/java/com/b6/mypaldotrip/domain/course/CustomCourseRepositoryTestConfig.java
  src/test/java/com/b6/mypaldotrip/domain/course/controller/CourseControllerTest.java
Labels: test

#163 fix : gitflows 수정
  .github/workflows/main-flow.yml
Labels: bugfix

#165 fix : gitflows 수정
  .github/workflows/main-flow.yml
Labels: bugfix

#168 https 연결로 인한 cors 설정
  src/main/java/com/b6/mypaldotrip/global/config/WebConfig.java
Labels: bugfix

#170 fix : 사용하지 않는 volume 삭제하도록 gitflows 수정
  .github/workflows/main-flow.yml
Labels: fix

#154 유저관련 테스트 코드 작성
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/ApplicationCheckReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/ApplicationSubmitReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/EmailSendReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/EmailVerifyReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/exception/EmailErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/EmailUtil.java
  src/test/java/com/b6/mypaldotrip/domain/user/ApplicationCommonTest.java
  src/test/java/com/b6/mypaldotrip/domain/user/controller/ApplicationControllerTest.java
  src/test/java/com/b6/mypaldotrip/domain/user/controller/EmailControllerTest.java
  src/test/java/com/b6/mypaldotrip/domain/user/controller/KakaoControllerTest.java
  src/test/java/com/b6/mypaldotrip/domain/user/service/EmailServiceTest.java
  src/test/java/com/b6/mypaldotrip/domain/user/service/EmailUtilTest.java
Labels: test

#155 여행정보 레포지토리, 엔티티 테스트 코드
  src/test/java/com/b6/mypaldotrip/domain/trip/TripCustomRepositoryTestConfig.java
  src/test/java/com/b6/mypaldotrip/domain/trip/TripTest.java
  src/test/java/com/b6/mypaldotrip/domain/trip/store/entity/TripEntityTest.java
  src/test/java/com/b6/mypaldotrip/domain/trip/store/repository/TripCustomRepositoryTest.java
  src/test/java/com/b6/mypaldotrip/domain/trip/store/repository/TripRepositoryTest.java
Labels: test

#156 CourseService TestCode
  src/main/java/com/b6/mypaldotrip/domain/course/service/CourseService.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/entity/CourseEntity.java
  src/test/java/com/b6/mypaldotrip/domain/course/CourseTest.java
  src/test/java/com/b6/mypaldotrip/domain/course/service/CourseServiceTest.java
Labels: fix, test

#173 CourseRepository TestCode작성
  src/test/java/com/b6/mypaldotrip/domain/course/CustomCourseRepositoryTestConfig.java
  src/test/java/com/b6/mypaldotrip/domain/course/store/repository/CustomCourseRepositoryTest.java
Labels: fix, test

#175 인기코스, 별점높은 여행지 캐싱
  src/main/java/com/b6/mypaldotrip/MypaldotripApplication.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/CourseController.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseListRes.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseListWrapper.java
  src/main/java/com/b6/mypaldotrip/domain/course/service/CourseService.java
  src/main/java/com/b6/mypaldotrip/domain/like/service/LikeService.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/TripController.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/request/TripListReq.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripListWrapper.java
  src/main/java/com/b6/mypaldotrip/domain/trip/service/TripService.java
  src/main/java/com/b6/mypaldotrip/global/config/CacheConfig.java
  src/test/java/com/b6/mypaldotrip/domain/course/controller/CourseControllerTest.java
  src/test/java/com/b6/mypaldotrip/domain/course/service/CourseServiceTest.java
  src/test/java/com/b6/mypaldotrip/domain/trip/controller/TripControllerTest.java
  src/test/java/com/b6/mypaldotrip/domain/trip/service/TripServiceTest.java
Labels: feat, fix, refactor, test

#172 fix : cors 설정
  src/main/java/com/b6/mypaldotrip/global/config/WebConfig.java
Labels: fix

#181 trip 도메인 권한 설정 추가
  src/main/java/com/b6/mypaldotrip/global/config/WebSecurityConfig.java
Labels: fix

#185 test : trip restdocs
  src/docs/asciidoc/index.adoc
Labels: test

#186 api 반환 값 변경 및 아스키독 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/b6/mypaldotrip/domain/user/controller/UserController.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/UserGetMyProfileRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/UserService.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/repository/UserRepository.java
  src/test/java/com/b6/mypaldotrip/domain/user/CommonTest.java
  src/test/java/com/b6/mypaldotrip/domain/user/controller/UserControllerTest.java
  src/test/java/com/b6/mypaldotrip/domain/user/service/UserServiceTest.java
  src/test/java/com/b6/mypaldotrip/domain/user/store/repository/UserRepositoryTest.java
Labels: fix

#187 코스생성시 연관된 여행정보 없이도 생성 가능, RestDocs 아스키독 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/b6/mypaldotrip/domain/course/service/CourseService.java
Labels: feat, test

#188 권한 설정 및 오류 수정
  src/main/java/com/b6/mypaldotrip/domain/sample/controller/SampleController.java
  src/main/java/com/b6/mypaldotrip/domain/sample/controller/dto/request/SampleReq.java
  src/main/java/com/b6/mypaldotrip/domain/sample/controller/dto/response/SampleRes.java
  src/main/java/com/b6/mypaldotrip/domain/sample/exception/SampleErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/sample/service/SampleService.java
  src/main/java/com/b6/mypaldotrip/domain/sample/store/entity/SampleEntity.java
  src/main/java/com/b6/mypaldotrip/domain/sample/store/repository/SampleRepository.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/UserUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/entity/UserEntity.java
  src/main/java/com/b6/mypaldotrip/global/config/WebConfig.java
  src/main/java/com/b6/mypaldotrip/global/config/WebSecurityConfig.java
Labels: fix

#189 연관된 여행정보 확인 로직 변경, 캐시 만료시간 변경
  src/main/java/com/b6/mypaldotrip/domain/course/service/CourseService.java
  src/main/java/com/b6/mypaldotrip/global/config/CacheConfig.java
Labels: fix

#191 bugfix : cors 오류 수정
  src/main/java/com/b6/mypaldotrip/global/config/WebConfig.java
Labels: bugfix
