Repository asdvsvs/my-paldo-trip, pull requests merged in 2024-01, with the labels that each got.

#2 초기설정
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/b6/mypaldotrip/domain/sample/controller/SampleController.java
  src/main/java/com/b6/mypaldotrip/domain/sample/controller/dto/request/SampleReq.java
  src/main/java/com/b6/mypaldotrip/global/common/GlobalResultCode.java
  src/main/java/com/b6/mypaldotrip/global/exception/GlobalExceptionHandler.java
  src/main/java/com/b6/mypaldotrip/global/response/RestResponse.java
Labels: bugfix, feat

#8 Spotless 자동화 적용
  build.gradle
  src/main/java/com/b6/mypaldotrip/MypaldotripApplication.java
  src/main/java/com/b6/mypaldotrip/domain/sample/controller/SampleController.java
  src/main/java/com/b6/mypaldotrip/domain/sample/controller/dto/request/SampleReq.java
  src/main/java/com/b6/mypaldotrip/domain/sample/controller/dto/response/SampleRes.java
  src/main/java/com/b6/mypaldotrip/domain/sample/exception/SampleErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/sample/store/repository/SampleRepository.java
  src/main/java/com/b6/mypaldotrip/global/common/BaseEntity.java
  src/main/java/com/b6/mypaldotrip/global/common/GlobalResultCode.java
  src/main/java/com/b6/mypaldotrip/global/config/JpaConfig.java
  src/main/java/com/b6/mypaldotrip/global/exception/GlobalExceptionHandler.java
  src/main/java/com/b6/mypaldotrip/global/response/RestResponse.java
  src/test/java/com/b6/mypaldotrip/MypaldotripApplicationTests.java
Labels: feat, fix

#14 Feat/trip
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/TripController.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/request/TripCreateReq.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/request/TripUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripCreateRes.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripDeleteRes.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripGetRes.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripListRes.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripUpdateRes.java
  src/main/java/com/b6/mypaldotrip/domain/trip/exception/TripErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/trip/service/TripService.java
  src/main/java/com/b6/mypaldotrip/domain/trip/store/entity/Category.java
  src/main/java/com/b6/mypaldotrip/domain/trip/store/entity/TripEntity.java
  src/main/java/com/b6/mypaldotrip/domain/trip/store/repository/TripRepository.java
Labels: feat

#16 [#15] feat : QueryDSL 설정 추가
  build.gradle
  gradlew
  src/main/java/com/b6/mypaldotrip/domain/course/controller/CourseController.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/requeset/CourseSaveReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/requeset/CourseUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseDeleteRes.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseGetRes.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseListRes.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseSaveRes.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseUpdateRes.java
  src/main/java/com/b6/mypaldotrip/domain/course/exception/CourseErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/course/service/CourseService.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/entity/CourseEntity.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/repository/CourseRepository.java
  src/main/java/com/b6/mypaldotrip/global/config/JpaConfig.java
Labels: feat

#22 [#1] feat : ci규칙에 spotless 추가
  .github/workflows/gradle.yml
Labels: feat

#21 Feat/city
  src/main/java/com/b6/mypaldotrip/domain/city/controller/CityController.java
  src/main/java/com/b6/mypaldotrip/domain/city/controller/dto/request/CityCreateReq.java
  src/main/java/com/b6/mypaldotrip/domain/city/controller/dto/request/CityUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/city/controller/dto/response/CityCreateRes.java
  src/main/java/com/b6/mypaldotrip/domain/city/controller/dto/response/CityDeleteRes.java
  src/main/java/com/b6/mypaldotrip/domain/city/controller/dto/response/CityListRes.java
  src/main/java/com/b6/mypaldotrip/domain/city/controller/dto/response/CityUpdateRes.java
  src/main/java/com/b6/mypaldotrip/domain/city/controller/dto/response/ProvinceListRes.java
  src/main/java/com/b6/mypaldotrip/domain/city/exception/CityErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/city/service/CityService.java
  src/main/java/com/b6/mypaldotrip/domain/city/store/entity/CityEntity.java
  src/main/java/com/b6/mypaldotrip/domain/city/store/repository/CityRepository.java
  src/main/java/com/b6/mypaldotrip/global/common/GlobalResultCode.java
  src/main/java/com/b6/mypaldotrip/global/exception/GlobalExceptionHandler.java
Labels: feat

#24 Feat/course
  .gitignore
  src/main/java/com/b6/mypaldotrip/domain/course/controller/CourseController.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/requeset/CourseUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/request/CourseSaveReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/request/CourseUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/service/CourseService.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/repository/CourseRepository.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/repository/CustomCourseRepository.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/repository/CustomCourseRepositoryImpl.java
  src/main/java/com/b6/mypaldotrip/domain/tripCourse/store/entity/TripCourse.java
Labels: feat, fix

#25 회원가입 인증인가 로그인 구현
  build.gradle
  src/main/java/com/b6/mypaldotrip/domain/user/controller/UserController.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/UserLonginReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/UserSignUpReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/UserLoginRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/UserSignUpRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/exception/UserErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/UserService.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/entity/User.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/repository/UserRepository.java
  src/main/java/com/b6/mypaldotrip/global/config/WebSecurityConfig.java
  src/main/java/com/b6/mypaldotrip/global/security/JwtAuthenticationFilter.java
  src/main/java/com/b6/mypaldotrip/global/security/JwtAuthorizationFilter.java
  src/main/java/com/b6/mypaldotrip/global/security/JwtUtil.java
  src/main/java/com/b6/mypaldotrip/global/security/UserDetailsImpl.java
  src/main/java/com/b6/mypaldotrip/global/security/UserDetailsServiceImpl.java
  src/main/resources/application.yml
Labels: feat

#29 bugfix : UserDetailsImpl 객체 사용 오류 해결
  src/main/java/com/b6/mypaldotrip/global/security/JwtAuthorizationFilter.java
Labels: bugfix

#33 회원 기능 및 S3 설정
  build.gradle
  src/main/java/com/b6/mypaldotrip/domain/user/controller/UserController.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/UserUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/UserDeleteRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/UserGetProfileRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/UserUpdateRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/UserService.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/entity/UserEntity.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/repository/UserRepository.java
  src/main/java/com/b6/mypaldotrip/global/common/BaseEntity.java
  src/main/java/com/b6/mypaldotrip/global/common/GlobalResultCode.java
  src/main/java/com/b6/mypaldotrip/global/common/S3Provider.java
  src/main/java/com/b6/mypaldotrip/global/config/S3Config.java
  src/main/java/com/b6/mypaldotrip/global/security/JwtAuthenticationFilter.java
  src/main/java/com/b6/mypaldotrip/global/security/UserDetailsImpl.java
  src/main/java/com/b6/mypaldotrip/global/security/UserDetailsServiceImpl.java
  src/main/resources/application.yml
Labels: feat, refactor

#34 여행정보와 도시 연관관계 설정 및 관련 로직 추가
  src/main/java/com/b6/mypaldotrip/domain/city/store/entity/CityEntity.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/request/TripCreateReq.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/request/TripUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripCreateRes.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripGetRes.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripListRes.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripUpdateRes.java
  src/main/java/com/b6/mypaldotrip/domain/trip/exception/TripErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/trip/service/TripService.java
  src/main/java/com/b6/mypaldotrip/domain/trip/store/entity/TripEntity.java
Labels: feat

#36 Comment 생성 기능 추가
  src/main/java/com/b6/mypaldotrip/domain/comment/controller/dto/CommentController.java
  src/main/java/com/b6/mypaldotrip/domain/comment/controller/dto/request/CommentSaveReq.java
  src/main/java/com/b6/mypaldotrip/domain/comment/controller/dto/response/CommentSaveRes.java
  src/main/java/com/b6/mypaldotrip/domain/comment/exception/CommentErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/comment/service/CommentService.java
  src/main/java/com/b6/mypaldotrip/domain/comment/store/entity/CommentEntity.java
  src/main/java/com/b6/mypaldotrip/domain/comment/store/repository/CommentRepository.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/entity/CourseEntity.java
Labels: bugfix, feat, fix

#40 좋아요 기능 추가, Course 와 연관관계 설정
  src/main/java/com/b6/mypaldotrip/domain/course/store/entity/CourseEntity.java
  src/main/java/com/b6/mypaldotrip/domain/like/controller/dto/LikeController.java
  src/main/java/com/b6/mypaldotrip/domain/like/controller/dto/response/LikeToggleRes.java
  src/main/java/com/b6/mypaldotrip/domain/like/service/LikeService.java
  src/main/java/com/b6/mypaldotrip/domain/like/store/entity/LikeEntity.java
  src/main/java/com/b6/mypaldotrip/domain/like/store/repository/LikeRepository.java
Labels: feat

#43 [#20] refactor : searchTripsAndSort 쿼리에서 조건검사 메서드 추출
  src/main/java/com/b6/mypaldotrip/domain/trip/store/repository/TripRepositoryImpl.java
Labels: refactor

#47 후기 CRUD 및 연관관계 설정
  src/main/java/com/b6/mypaldotrip/domain/review/controller/ReviewController.java
  src/main/java/com/b6/mypaldotrip/domain/review/controller/dto/request/ReviewCreateReq.java
  src/main/java/com/b6/mypaldotrip/domain/review/controller/dto/request/ReviewListReq.java
  src/main/java/com/b6/mypaldotrip/domain/review/controller/dto/request/ReviewUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/review/controller/dto/response/ReviewCreateRes.java
  src/main/java/com/b6/mypaldotrip/domain/review/controller/dto/response/ReviewDeleteRes.java
  src/main/java/com/b6/mypaldotrip/domain/review/controller/dto/response/ReviewListRes.java
  src/main/java/com/b6/mypaldotrip/domain/review/controller/dto/response/ReviewUpdateRes.java
  src/main/java/com/b6/mypaldotrip/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/review/service/ReviewService.java
  src/main/java/com/b6/mypaldotrip/domain/review/store/entity/ReviewEntity.java
  src/main/java/com/b6/mypaldotrip/domain/review/store/repository/ReviewRepository.java
  src/main/java/com/b6/mypaldotrip/domain/trip/store/entity/TripEntity.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/entity/UserEntity.java
  src/main/java/com/b6/mypaldotrip/global/config/WebSecurityConfig.java
Labels: feat

#52 유저 역할 추가
  src/main/java/com/b6/mypaldotrip/domain/user/store/entity/UserEntity.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/entity/UserRole.java
  src/main/java/com/b6/mypaldotrip/global/template/ResultCode.java
Labels: feat

#49 [#45] feat : 후기 조회 정렬 기능 구현
  src/main/java/com/b6/mypaldotrip/domain/review/controller/dto/request/ReviewListReq.java
  src/main/java/com/b6/mypaldotrip/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/review/service/ReviewService.java
  src/main/java/com/b6/mypaldotrip/domain/review/store/entity/ReviewSort.java
  src/main/java/com/b6/mypaldotrip/domain/review/store/repository/ReviewCustomRepository.java
  src/main/java/com/b6/mypaldotrip/domain/review/store/repository/ReviewRepository.java
  src/main/java/com/b6/mypaldotrip/domain/review/store/repository/ReviewRepositoryImpl.java
Labels: feat

#54 Course 페이징 및 정렬
  src/main/java/com/b6/mypaldotrip/domain/comment/controller/CommentController.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/CourseController.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/request/CourseSearchReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/exception/CourseErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/course/service/CourseService.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/entity/CourseEntity.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/entity/CourseSort.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/repository/CustomCourseRepository.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/repository/CustomCourseRepositoryImpl.java
  src/main/java/com/b6/mypaldotrip/domain/like/controller/LikeController.java
Labels: feat, fix, refactor

#50 이메일 인증 구현
  build.gradle
  src/main/java/com/b6/mypaldotrip/domain/user/controller/EmailController.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/EmailSendReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/EmailVerifyReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/EmailSendRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/EmailVerifyRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/exception/EmailErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/user/exception/UserErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/EmailAuthService.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/EmailService.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/EmailUtil.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/UserService.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/entity/EmailAuth.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/repository/EmailAuthRepository.java
  src/main/java/com/b6/mypaldotrip/global/config/EmailConfig.java
  src/main/java/com/b6/mypaldotrip/global/config/RedisConfig.java
  src/main/java/com/b6/mypaldotrip/global/config/WebSecurityConfig.java
  src/main/java/com/b6/mypaldotrip/global/security/JwtAuthorizationFilter.java
  src/main/resources/application.yml
Labels: bugfix, feat, refactor

#56 유저 팔로우 기능 구현
  src/main/java/com/b6/mypaldotrip/domain/follow/controller/FollowController.java
  src/main/java/com/b6/mypaldotrip/domain/follow/controller/dto/response/FollowToggleRes.java
  src/main/java/com/b6/mypaldotrip/domain/follow/exception/FollowErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/follow/service/FollowService.java
  src/main/java/com/b6/mypaldotrip/domain/follow/store/entity/FollowerEntity.java
  src/main/java/com/b6/mypaldotrip/domain/follow/store/entity/FollowingEntity.java
  src/main/java/com/b6/mypaldotrip/domain/follow/store/repository/FollowerRepository.java
  src/main/java/com/b6/mypaldotrip/domain/follow/store/repository/FollowingRepository.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/entity/UserEntity.java
Labels: feat

#57 유저 등급 순 후기 정렬 및 팔로잉 유저 후기 필터링 구현
  src/main/java/com/b6/mypaldotrip/domain/review/controller/ReviewController.java
  src/main/java/com/b6/mypaldotrip/domain/review/controller/dto/request/ReviewListReq.java
  src/main/java/com/b6/mypaldotrip/domain/review/controller/dto/response/ReviewListRes.java
  src/main/java/com/b6/mypaldotrip/domain/review/service/ReviewService.java
  src/main/java/com/b6/mypaldotrip/domain/review/store/entity/ReviewSort.java
  src/main/java/com/b6/mypaldotrip/domain/review/store/repository/ReviewCustomRepository.java
  src/main/java/com/b6/mypaldotrip/domain/review/store/repository/ReviewRepositoryImpl.java
Labels: feat

#62 Comment 전체조회, 팔로우한 유저별 페이징 구현, 등급별 정렬 구현
  src/main/java/com/b6/mypaldotrip/domain/comment/controller/CommentController.java
  src/main/java/com/b6/mypaldotrip/domain/comment/controller/dto/request/CommentSearchReq.java
  src/main/java/com/b6/mypaldotrip/domain/comment/controller/dto/response/CommentListRes.java
  src/main/java/com/b6/mypaldotrip/domain/comment/exception/CommentErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/comment/service/CommentService.java
  src/main/java/com/b6/mypaldotrip/domain/comment/store/entity/CommentSort.java
  src/main/java/com/b6/mypaldotrip/domain/comment/store/repository/CommentRepository.java
  src/main/java/com/b6/mypaldotrip/domain/comment/store/repository/CustomCommentRepository.java
  src/main/java/com/b6/mypaldotrip/domain/comment/store/repository/CustomCommentRepositoryImpl.java
Labels: feat

#64 카카오 로그인
  build.gradle
  src/main/java/com/b6/mypaldotrip/domain/user/controller/KakaoController.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/UserSignUpReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/KakaoService.java
  src/main/java/com/b6/mypaldotrip/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/images/kakao_login_button.png
  src/main/resources/templates/kakao.html
Labels: feat

#66 유저 역할 변경 신청 및 변경 구현
  src/main/java/com/b6/mypaldotrip/domain/user/controller/ApplicationController.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/ApplicationCheckReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/ApplicationSubmitReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/ApplicationConfirmRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/ApplicationGetListRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/ApplicationGetRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/ApplicationSubmitRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/exception/ApplicationErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/ApplicationService.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/UserService.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/entity/ApplicationEntity.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/entity/UserEntity.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/repository/ApplicationRepository.java
  src/main/java/com/b6/mypaldotrip/global/security/UserDetailsImpl.java
Labels: feat

#59 Course 비회원도 조회 가능, 팔로우한 유저별 게시글 페이징 구현, 게시글관리 권한 부여
  src/main/java/com/b6/mypaldotrip/domain/course/controller/CourseController.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/request/CourseSearchReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/exception/CourseErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/course/service/CourseService.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/entity/CourseSort.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/repository/CustomCourseRepository.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/repository/CustomCourseRepositoryImpl.java
  src/main/java/com/b6/mypaldotrip/global/config/WebSecurityConfig.java
Labels: feat, fix

#65 여행정보 도메인 추가 기능 구현 (권한 검증, 정렬 기능)
  src/main/java/com/b6/mypaldotrip/domain/review/service/ReviewService.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/TripController.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/request/TripListReq.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripListRes.java
  src/main/java/com/b6/mypaldotrip/domain/trip/exception/TripErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/trip/service/TripService.java
  src/main/java/com/b6/mypaldotrip/domain/trip/store/entity/TripEntity.java
  src/main/java/com/b6/mypaldotrip/domain/trip/store/entity/TripSort.java
  src/main/java/com/b6/mypaldotrip/domain/trip/store/repository/TripCustomRepository.java
  src/main/java/com/b6/mypaldotrip/domain/trip/store/repository/TripRepositoryImpl.java
Labels: feat

#69 유저 목록 조회 기능 구현
  src/main/java/com/b6/mypaldotrip/domain/follow/store/entity/FollowerEntity.java
  src/main/java/com/b6/mypaldotrip/domain/follow/store/entity/FollowingEntity.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/UserController.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/UserListReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/UserListRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/exception/UserErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/UserService.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/entity/UserEntity.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/entity/UserSort.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/repository/UserCustomRepository.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/repository/UserCustomRepositoryImpl.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/repository/UserRepository.java
  src/main/java/com/b6/mypaldotrip/global/config/WebSecurityConfig.java
Labels: bugfix, feat

#73 fix : Comment 목록조회 response 항목 수정
  src/main/java/com/b6/mypaldotrip/domain/comment/controller/dto/response/CommentListRes.java
  src/main/java/com/b6/mypaldotrip/domain/comment/service/CommentService.java
  src/main/java/com/b6/mypaldotrip/domain/comment/store/entity/CommentEntity.java
  src/main/java/com/b6/mypaldotrip/domain/comment/store/repository/CustomCommentRepositoryImpl.java
Labels: fix

#72 여행정보 파일 첨부 기능
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/TripController.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripCreateRes.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripGetRes.java
  src/main/java/com/b6/mypaldotrip/domain/trip/service/TripService.java
  src/main/java/com/b6/mypaldotrip/domain/trip/store/entity/TripEntity.java
  src/main/java/com/b6/mypaldotrip/domain/tripFile/controller/TripFileController.java
  src/main/java/com/b6/mypaldotrip/domain/tripFile/controller/dto/TripFileGetRes.java
  src/main/java/com/b6/mypaldotrip/domain/tripFile/controller/dto/response/TripFileDeleteRes.java
  src/main/java/com/b6/mypaldotrip/domain/tripFile/controller/dto/response/TripFileListRes.java
  src/main/java/com/b6/mypaldotrip/domain/tripFile/controller/dto/response/TripFileUploadRes.java
  src/main/java/com/b6/mypaldotrip/domain/tripFile/exception/TripFileErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/tripFile/service/TripFileService.java
  src/main/java/com/b6/mypaldotrip/domain/tripFile/store/entity/TripFileEntity.java
  src/main/java/com/b6/mypaldotrip/domain/tripFile/store/repository/TripFileRepository.java
Labels: feat, fix, refactor

#78 컬력센 중복 조인 문제와 프론트 구현 중 문제
  build.gradle
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/TripController.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/KakaoController.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/UserController.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/UserListReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/UserListRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/UserService.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/entity/UserEntity.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/repository/UserCustomRepository.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/repository/UserCustomRepositoryImpl.java
  src/main/java/com/b6/mypaldotrip/global/common/GlobalResultCode.java
  src/main/java/com/b6/mypaldotrip/global/config/WebConfig.java
  src/main/java/com/b6/mypaldotrip/global/config/WebSecurityConfig.java
  src/main/java/com/b6/mypaldotrip/global/security/JwtAuthorizationFilter.java
  src/main/resources/application.yml
Labels: feat, fix

#71 Course File 업로드 ,조회, 삭제
  src/main/java/com/b6/mypaldotrip/domain/course/controller/CourseController.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseGetRes.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseListRes.java
  src/main/java/com/b6/mypaldotrip/domain/course/service/CourseService.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/entity/CourseEntity.java
  src/main/java/com/b6/mypaldotrip/domain/courseFile/controller/CourseFileController.java
  src/main/java/com/b6/mypaldotrip/domain/courseFile/controller/dto/response/CourseFileAddRes.java
  src/main/java/com/b6/mypaldotrip/domain/courseFile/controller/dto/response/CourseFileDeleteRes.java
  src/main/java/com/b6/mypaldotrip/domain/courseFile/controller/dto/response/CourseFileListRes.java
  src/main/java/com/b6/mypaldotrip/domain/courseFile/exception/CourseFileErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/courseFile/service/CourseFileService.java
  src/main/java/com/b6/mypaldotrip/domain/courseFile/store/entity/CourseFileEntity.java
  src/main/java/com/b6/mypaldotrip/domain/courseFile/store/repository/CourseFileRepository.java
Labels: feat, fix

#81 Feat/workflows
  .github/workflows/dev-flow.yml
  .github/workflows/main-flow.yml
Labels: feat

#82 fix : 주석 제거
  .github/workflows/main-flow.yml
Labels: fix

#80 프론트엔드와 연동, 인가 작업, QueryDsl fetch작업
  src/main/java/com/b6/mypaldotrip/domain/comment/controller/CommentController.java
  src/main/java/com/b6/mypaldotrip/domain/comment/controller/dto/response/CommentListRes.java
  src/main/java/com/b6/mypaldotrip/domain/comment/service/CommentService.java
  src/main/java/com/b6/mypaldotrip/domain/comment/store/repository/CustomCommentRepository.java
  src/main/java/com/b6/mypaldotrip/domain/comment/store/repository/CustomCommentRepositoryImpl.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/CourseController.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/request/CourseSearchReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseGetRes.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseListRes.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseSaveRes.java
  src/main/java/com/b6/mypaldotrip/domain/course/service/CourseService.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/repository/CustomCourseRepository.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/repository/CustomCourseRepositoryImpl.java
  src/main/java/com/b6/mypaldotrip/domain/courseFile/controller/CourseFileController.java
  src/main/java/com/b6/mypaldotrip/domain/courseFile/exception/CourseFileErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/courseFile/service/CourseFileService.java
  src/main/java/com/b6/mypaldotrip/domain/like/controller/LikeController.java
  src/main/java/com/b6/mypaldotrip/domain/like/controller/dto/response/LikeCheckRes.java
  src/main/java/com/b6/mypaldotrip/domain/like/service/LikeService.java
  src/main/java/com/b6/mypaldotrip/global/config/WebSecurityConfig.java
Labels: feat, fix

#84 여행정보 및 후기 프론트엔드 맞춤 변경사항 적용
  src/main/java/com/b6/mypaldotrip/domain/review/controller/ReviewController.java
  src/main/java/com/b6/mypaldotrip/domain/review/controller/dto/response/ReviewListRes.java
  src/main/java/com/b6/mypaldotrip/domain/review/service/ReviewService.java
  src/main/java/com/b6/mypaldotrip/domain/review/store/entity/ReviewSort.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/TripController.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripGetRes.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripListRes.java
  src/main/java/com/b6/mypaldotrip/domain/trip/service/TripService.java
  src/main/java/com/b6/mypaldotrip/domain/trip/store/entity/TripEntity.java
  src/main/java/com/b6/mypaldotrip/domain/trip/store/repository/TripRepositoryImpl.java
Labels: feat, fix

#111 배포 환경에서 카카오 로그인 버그 수정
  src/main/java/com/b6/mypaldotrip/domain/user/controller/KakaoController.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/KakaoService.java
  src/main/resources/application.yml
  src/main/resources/templates/kakao.html
Labels: bugfix

#112 댓글 생성, 목록조회 반환값 추가
  src/main/java/com/b6/mypaldotrip/domain/comment/controller/CommentController.java
  src/main/java/com/b6/mypaldotrip/domain/comment/controller/dto/request/CommentUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/comment/controller/dto/response/CommentListRes.java
  src/main/java/com/b6/mypaldotrip/domain/comment/service/CommentService.java
Labels: feat

#121 내정보 보기 api 및 기타 변경
  src/main/java/com/b6/mypaldotrip/domain/user/controller/UserController.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/UserUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/UserGetMyProfileRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/UserService.java
Labels: feat, fix

#119 좋아요 동시성 테스트 완료
  src/test/java/com/b6/mypaldotrip/concurrencyTest/LikeConcurrencyTest.java
Labels: test

#120 코스 생성시 코스-트립 중간테이블 생성, 코스 단건조회시 연관된 트립id 반환
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/request/CourseSaveReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseGetRes.java
  src/main/java/com/b6/mypaldotrip/domain/course/service/CourseService.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/entity/CourseEntity.java
  src/main/java/com/b6/mypaldotrip/domain/tripCourse/store/repository/TripCourseRepository.java
Labels: feat

#124 프론트 및 update메서드, s3 코드 변경
  src/main/java/com/b6/mypaldotrip/domain/course/controller/CourseController.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/request/CourseUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseGetRes.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseListRes.java
  src/main/java/com/b6/mypaldotrip/domain/course/service/CourseService.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/entity/CourseEntity.java
  src/main/java/com/b6/mypaldotrip/domain/courseFile/service/CourseFileService.java
Labels: feat, fix

#123 fix : 여행정보 목록 조회 시 파일 URL 리스트 반환
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/response/TripListRes.java
  src/main/java/com/b6/mypaldotrip/domain/trip/service/TripService.java
Labels: fix

#126 유저 기능 수정
  src/main/java/com/b6/mypaldotrip/domain/follow/controller/dto/response/FollowRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/UserController.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/UserGetMyProfileRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/response/UserGetProfileRes.java
  src/main/java/com/b6/mypaldotrip/domain/user/service/UserService.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/entity/UserEntity.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/repository/UserCustomRepository.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/repository/UserCustomRepositoryImpl.java
  src/main/java/com/b6/mypaldotrip/domain/user/store/repository/UserRepository.java
Labels: feat, fix

#128 fix : 유저네임 유니크 설정
  src/main/java/com/b6/mypaldotrip/domain/user/store/entity/UserEntity.java
Labels: fix

#129 feat : 여행정보 이름으로 검색 메서드 추가
  src/main/java/com/b6/mypaldotrip/domain/trip/service/TripService.java
Labels: feat

#130 fix : 여행정보 생성 및 수정 시 도시 이름을 입력하도록 변경
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/request/TripCreateReq.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/request/TripUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/trip/service/TripService.java
Labels: fix

#131 Course 여행정보 등록 요구사항 id -> 이름으로 변경, 오류 수정
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/request/CourseSaveReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/request/CourseUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/course/controller/dto/response/CourseGetRes.java
  src/main/java/com/b6/mypaldotrip/domain/course/service/CourseService.java
  src/main/java/com/b6/mypaldotrip/domain/course/store/entity/CourseEntity.java
Labels: bugfix, fix

#138 유저 테스트 코드 작성
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/UserListReq.java
  src/main/java/com/b6/mypaldotrip/domain/user/controller/dto/request/UserUpdateReq.java
  src/test/java/com/b6/mypaldotrip/domain/user/CommonControllerTest.java
  src/test/java/com/b6/mypaldotrip/domain/user/CommonTest.java
  src/test/java/com/b6/mypaldotrip/domain/user/controller/UserControllerTest.java
  src/test/java/com/b6/mypaldotrip/domain/user/service/UserServiceTest.java
  src/test/java/com/b6/mypaldotrip/domain/user/store/repository/UserCustomRepositoryTest.java
  src/test/java/com/b6/mypaldotrip/domain/user/store/repository/UserRepositoryTest.java
Labels: fix, test

#140 여행정보 컨트롤러 테스트 코드
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/request/TripCreateReq.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/request/TripListReq.java
  src/main/java/com/b6/mypaldotrip/domain/trip/controller/dto/request/TripUpdateReq.java
  src/main/java/com/b6/mypaldotrip/domain/trip/exception/TripErrorCode.java
  src/main/java/com/b6/mypaldotrip/domain/trip/service/TripService.java
  src/test/java/com/b6/mypaldotrip/domain/trip/TripTest.java
  src/test/java/com/b6/mypaldotrip/domain/trip/TripTestUtils.java
  src/test/java/com/b6/mypaldotrip/domain/trip/controller/TripControllerTest.java
Labels: test
